version: "2"
checks:
  similar-code:
    config:
      threshold: 4
  identical-code:
    config:
      threshold: 4
plugins:
  radon:
    enabled: true
  pep8:
    enabled: true
exclude_patterns:
  - "scripts/online/"
  - "scripts/offline/"