language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then .build/pre_script_code_climate.sh; fi
script:
  - .build/build.sh
after_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then .build/post_script_code_climate.sh; fi

matrix:
  allow_failures:
    - python: nightly
cache: pip
