language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.6-dev
  - 3.7-dev
  - nightly
# command to install dependencies
install:
  - make pip3-all
script:
  - make quality
after_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then make code-climate codecov codacy; fi

matrix:
  allow_failures:
    - python: 3.6-dev
    - python: 3.7-dev
    - python: nightly
cache: pip
