language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.6-dev
  - 3.7
  - 3.7-dev
  - nightly
# command to install dependencies
install:
  - make pip3-all
script:
  - make coverage

matrix:
  allow_failures:
    - python: 3.6-dev
    - python: 3.7
    #- python: 3.7-dev python 3.7 finally fixed :-)
    - python: nightly
cache: pip
