language: python
python:
  - 3.4
  - 3.5-dev
  - 3.6-dev
  - 3.7-dev
  - nightly
# command to install dependencies
install:
  - make pip3-all
script:
  - make unittest

matrix:
  allow_failures:
    - python: nightly
cache: pip
