replace_nothing:
  text: |
    [[RE:Target|Target]]
  redirect: "Redirect"
  target: "Target"
  expect: |
    [[RE:Target|Target]]
replace_simple_link:
  text: |
    [[RE:Redirect|Redirect]]
    [[RE:Redirect]]
  redirect: "Redirect"
  target: "Target"
  expect: |
    [[RE:Target|Redirect]]
    [[RE:Target]]
replace_re_siehe:
  text: |
    {{RE siehe|Redirect}}
    {{RE siehe|Redirect|Something else}}
  redirect: "Redirect"
  target: "Target"
  expect: |
    {{RE siehe|Target|Redirect}}
    {{RE siehe|Target|Something else}}
replace_braces:
  text: |
    {{RE siehe|Redirect (test)}}
    {{RE siehe|Redirect (test)|Something else}}
    [[RE:Redirect (test)|Redirect]]
    [[RE:Redirect (test)]]
  redirect: "Redirect (test)"
  target: "Target"
  expect: |
    {{RE siehe|Target|Redirect (test)}}
    {{RE siehe|Target|Something else}}
    [[RE:Target|Redirect]]
    [[RE:Target]]
replace_vorgänger:
  text: |
    {{REDaten
    |VORGÄNGER=Redirect (with braces)
    |NACHFOLGER=Something
    }}
  redirect: "Redirect (with braces)"
  target: "Target"
  expect: |
    {{REDaten
    |VORGÄNGER=Target
    |NACHFOLGER=Something
    }}
replace_nachfolger:
  text: |
    {{REDaten
    |VORGÄNGER=Something
    |NACHFOLGER=Redirect (with braces)
    }}
  redirect: "Redirect (with braces)"
  target: "Target"
  expect: |
    {{REDaten
    |VORGÄNGER=Something
    |NACHFOLGER=Target
    }}
