short_descrition_found:
  text: |
    {{REDaten
    |BAND=I,1
    |KURZTEXT=kurzer Text
    }}
    text.
    {{REAutor|OFF}}
  test_number: 0
  result:
    - short_description: "kurzer Text"
    - []

no_short_descrition:
  text: |
    {{REDaten
    |BAND=I,1
    |KURZTEXT=
    }}
    text.
    {{REAutor|OFF}}
  test_number: 0
  result:
    - {}
    - ["short_description"]

with_appendix:
  text: |
    {{REDaten
    |BAND=I,1
    |KURZTEXT=Blub
    }}
    text.
    {{REAutor|OFF}}
    {{REDaten
    |BAND=S I
    |KURZTEXT=
    }}
    text.
    {{REAutor|OFF}}
  test_number: 1
  result:
    - short_description: "Blub"
    - []
