redirect_found:
  text: |
    {{REDaten
    |BAND=I,1
    |VERWEIS=ON
    }}
    text.
    {{REAutor|OFF}}
  result:
    - redirect: true
    - []

no_redirect:
  text: |
    {{REDaten
    |BAND=I,1
    |VERWEIS=OFF
    }}
    text.
    {{REAutor|OFF}}
  result:
    - {}
    - ["redirect"]

fetch_a_real_link_from_template:
  text: |
    {{REDaten
    |BAND=I,1
    |VERWEIS=ON
    }}
    '''Ad Algam''' s. {{SperrSchrift|{{RE siehe|Turris ad Algam}}}}.
    {{REAutor|OFF}}
  result:
    - redirect: "Turris ad Algam"
    - []
