version: 2
jobs:
  quality:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make pip3-all
      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: run unittest
          when: always
          command: |
            . venv/bin/activate
            make coverage
      - run:
          name: flake8
          when: always
          command: |
            . venv/bin/activate
            make flake8
      - run:
          name: pycodestyle
          when: always
          command: |
            . venv/bin/activate
            make pycodestyle
      - run:
          name: pylint
          when: always
          command: |
            . venv/bin/activate
            make pylint
      - run:
          name: safety
          when: always
          command: |
            . venv/bin/activate
            make safety
  coverage:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: pre target code climate
          command: |
            . venv/bin/activate
            make code-climate-pre
      - run:
          name: run coverage
          command: |
            . venv/bin/activate
            make coverage
      - run:
          name: report code climate
          command: |
            . venv/bin/activate
            make code-climate-post
      - run:
          name: report codacy
          command: |
            . venv/bin/activate
            make codacy
      - run:
          name: report codecov
          command: |
            . venv/bin/activate
            make codecov
workflows:
  version: 2
  test-and-quality:
    jobs:
      - quality
      - coverage:
          requires:
            - quality