version: 2

# define first all the single commands ... for reuse

restore_cache: &restore_cache
  restore_cache:
    keys:
      - v7-dependencies-{{ .Environment.PYTHON_VERSION }}-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "requirements.txt" }}
      - v7-dependencies-{{ .Environment.PYTHON_VERSION }}-{{ .Environment.CIRCLE_BRANCH }}-
      - v7-dependencies-{{ .Environment.PYTHON_VERSION }}-

save_cache: &save_cache
  save_cache:
    paths:
      - ./venv
    key: v7-dependencies-{{ .Environment.PYTHON_VERSION }}-{{ .Environment.CIRCLE_BRANCH }}-{{ checksum "requirements.txt" }}

install_dependencies: &install_dependencies
  run:
    name: install dependencies
    command: |
      python3 -m venv venv
      . venv/bin/activate
      make pip3
      pip list

run_unittest: &run_unittest
  run:
    name: run unittest
    when: always
    command: |
      . venv/bin/activate
      make unittest

flake8: &flake8
  run:
    name: flake8
    when: always
    command: |
      . venv/bin/activate
      make flake8

pycodestyle: &pycodestyle
  run:
    name: pycodestyle
    when: always
    command: |
      . venv/bin/activate
      make pycodestyle

pylint: &pylint
  run:
    name: pylint
    when: always
    command: |
      . venv/bin/activate
      make pylint

safety: &safety
  run:
    name: safety
    when: always
    command: |
      . venv/bin/activate
      make safety

run_coverage: &run_coverage
  run:
    name: run coverage
    command: |
      . venv/bin/activate
      make coverage

report_codacy: &report_codacy
  run:
    name: report codacy
    command: |
      . venv/bin/activate
      make codacy

report_codecov: &report_codecov
  run:
    name: report codecov
    command: |
      . venv/bin/activate
      codecov -F $PYTHON_VERSION

show_python_version: &show_python_version
  run:
    name: python version
    command: |
      python -c "import sys; print (sys.version)"

quality_steps: &quality_steps
  steps:
    - checkout
    - <<: *restore_cache
    - <<: *show_python_version
    - <<: *install_dependencies
    - <<: *save_cache
    - <<: *flake8
    - <<: *pycodestyle
    - <<: *pylint
    - <<: *safety

version_steps: &version_steps
  steps:
    - checkout
    - <<: *restore_cache
    - <<: *show_python_version
    - <<: *install_dependencies
    - <<: *save_cache
    - <<: *run_unittest

coverage_steps: &coverage_steps
  steps:
    - checkout
    - <<: *restore_cache
    - <<: *show_python_version
    - <<: *run_coverage
    - <<: *report_codacy
    - <<: *report_codecov

# job definitions

jobs:
  quality:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    <<: *quality_steps

  version35:
    docker:
      - image: circleci/python:3.5
    working_directory: ~/repo
    <<: *version_steps

  version37:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    <<: *version_steps

  version38:
    docker:
      - image: circleci/python:3.8-rc
    working_directory: ~/repo
    <<: *version_steps

  coverage35:
    docker:
      - image: circleci/python:3.5
    working_directory: ~/repo
    <<: *coverage_steps

  coverage37:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    <<: *coverage_steps

# dependencies for the workflow

workflows:
  version: 2
  test-and-quality:
    jobs:
      - quality:
          context: python37
      - version35:
          context: python35
      - version37:
          context: python37
      - version38:
          context: python38
      - coverage35:
          context: python35
          requires:
            - version35
            - quality
      - coverage37:
          context: python37
          requires:
            - version37
            - quality