version: 2
jobs:
  pip3:
    docker:
      - image: circleci/python:3.6.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
          - v1-dependencies-{{ checksum "requirements.txt" }}-
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make pip3-all
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
  static quality:
    docker:
      - image: circleci/python:3.6.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: flake8
          when: always
          command: |
            . venv/bin/activate
            make flake8
      - run:
          name: pylint
          when: always
          command: |
            . venv/bin/activate
            make pylint
      - run:
          name: safety
          when: always
          command: |
            . venv/bin/activate
            make safety
  coverage:
    docker:
      - image: circleci/python:3.6.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: run coverage
          command: |
            . venv/bin/activate
            make coverage
      - run:
          name: run codacy
          command: |
            . venv/bin/activate
            make codacy

      - run:
          name: run codecov
          command: |
            . venv/bin/activate
            make codecov
workflows:
  version: 2
  test-and-quality:
    jobs:
      - pip3
      - coverage:
          requires:
            - pip3
      - static quality:
          requires:
            - pip3