in_the_middle:
  given:
    issue: I A,1
    page: 127
    title: Ragando
    start: True
    end: False
  expect: |
    '''Ragando,''' ein Ort in [[RE:Noricum|Noricum]], nach {{RE siehe|Itinerarien|Itin.}} Ant. 129 ([[RE:Abi|Abi]].) ''Ragundone'', nach [[RE:Tabula Peutingeriana|Tab. Peut.]] ''Ragandone'', nach Itin. Hieros. 560 ''Ragindone'', in der Mitte zwischen [[RE:Celeia|Celeia]] (Cilli) und {{RE siehe|Poetovio}} (Pettau) gelegen, nach Itin. Ant. und Tab. Peut. je 18, nach Itin. Hieros. (auf Umwegen) je 24 röm. Meilen von beiden Städten entfernt, also im südöstlichen Steiermark, nach CIL III p. 645<ref name="CIL 3p|645">[https://cil.bbaw.de/hauptnavigation/das-cil/baende CORPUS INSCRIPTIONUM LATINARUM I{{sup|2}} ff.] 645</ref> bei Loßnitz, nach der angehängten {{SperrSchrift|Kiepert}} sehen Karte bei Studenitz.
last_article_on_page:
  given:
    issue: I A,1
    page: 127
    title: Ragonius
    start: True
    end: False
  expect: |
    '''Ragonius.''' Für diesen Familiennamen finden sich Belege vom Ende des 2. bis zum Ende des 4. Jhdts. Die frühesten Vertreter des etruskischer Wurzel entstammenden Namens ({{SperrSchrift|Schulze}} Lat. Eigenn. 367) fügen dem Gentilicium die ,sicher etruskischen Nomina ''Larcius'' und ''Urinatius¹'' (letzteres vom früh verschwundenen kampanischen Stadtnamen ''Uria'' ({{RE siehe|Nola}}) abgeleitet, auf römischen Inschriften sonst nur einmal CIL VI 2086,<ref name="CIL 6|2086">{{CIL|6|2086}}.</ref> auf etruskischen in der Form ''urinate'' sehr häufig, z. B. CIE 109f. 163. 1228ff.), sowie den aus dem
end_of_article:
  given:
    issue: I A,1
    page: 127
    title: Something
    start: False
    end: True
  expect: |
    ﻿127 {{Polytonisch|sup€λsupΡάγαεα}}

    gegangen, das nicht nur in syr. ''Razïküiâ'' und neupers. ''Râxï'' ,Mann aus ''Rai{{sup|(}}'' weiterlebt, sondern wohl auch in {{Polytonisch|Ῥαζήχ}} (Acta mart. Ana-stasii ed. U s e n e r Bonn 1894 p. 2 b und p. 5 b) und der Ableitung {{Polytonisch|Ῥαζακηνή}} (Theophyl. Simok. III 18, 6) vorliegt. Von den wechselvollen Schicksalen der Stadt im Mittelalter sei hier nur hervorgehoben, daß sie i. J. 863 durch ein Erdbeben zerstört wurde und nochmals unter Sähruh (1404–1447) für kurze Zeit als Residenz eine Nachblüte erlebte. Seitdem ist sie vollständig verfallen. Das Ruinenfeld, 5 engl. Meilen südöstlich von Tehran, läßt noch die Stadtmauern mit einigen ihrer Türme und die Akropolis im Nordosten erkennen. Eine genaue Untersuchung mit umfassenden Ausgrabungen würde sich voraussichtlich sehr belohnt machen. Vgl. Ritter Erdkunde VIII 5951 {{SperrSchrift|Curzon}} Persia I 345ff., Lond. 1892. [[Josef Markwart|{{SperrSchrift|Marquart}}]] Eränsahr (Abh. Gott. Ges. d. W. N. F. III no. 2) 122ff. und [[Philologus|Philologus]] Suppl. X 19ff. Jackson Persia 4280., New-Vork 1906. Derselbe [[RE:Spiegel|Spiegel]] Memorial Volume 237ff., Bombay 1908.
