name: Dependencies
description: Prepares Python and downloads dependencies

runs:
  using: composite

  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Install the project
      run: uv sync --locked --all-extras --dev
      shell: sh
    - name: Display Python version and Dependencies
      run: python -c "import sys; print(sys.version)" && uv tree
      shell: sh