name: Integration test

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the workflow every day at midnight UTC

permissions:
  contents: read
  id-token: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        uses: "./.github/actions/dependencies"
      - name: flake8
        run: make flake8
      - name: pycodestyle
        run: make pycodestyle
        if: always()
      - name: pylint
        run: make pylint
        if: always()
      - name: mypy
        run: make mypy
        if: always()
  wikitest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        partition: [0]
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        uses: "./.github/actions/dependencies"
      - name: wikitest
        env:
          WS_REAL_WIKI: 1
          WS_REAL_WIKI_PART: "${{ matrix.partition }}"
          WS_REAL_WIKI_PARTITIONS: 1
          PYTHONUNBUFFERED: 1
        run: nose2 -v --with-coverage && coverage xml
      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          flags: "wiki${{ matrix.partition }}"
        if: always()