name: Quality

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Dependencies
        uses: "./.github/actions/dependencies"
      - name: ruff
        run: make ruff
      - name: ruff-format-check
        run: make ruff-format-check
        if: always()
      - name: ty
        run: make ty
        if: always()
