name: Python lint and test

on:
  pull_request:

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        uses: "./.github/actions/dependencies"
      - name: flake8
        run: make flake8
      - name: pycodestyle
        run: make pycodestyle
      - name: pylint
        run: make pylint
      - name: mypy
        run: make mypy
  wikitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        uses: "./.github/actions/dependencies"
      - name: wikitest
        env:
          WS_REAL_WIKI: 1
        run: nose2 -v --with-coverage && coverage xml
      - name: Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true