name: Python lint and test

on:
  pull_request:

permissions:
  contents: read

jobs:
  quality:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: make pip3-dev
      - name: Display Python version and Dependencies
        run: python -c "import sys; print(sys.version)" && pip list
      - name: flake8
        run: make flake8
      - name: pycodestyle
        run: make pycodestyle
      - name: pylint
        run: make pylint
      - name: mypy
        run: make mypy