name: Python lint and test

on:
  pull_request:

permissions:
  contents: read

jobs:
  quality:

    runs-on: ubuntu-latest

    steps:
      - name: Dependencies
        uses: "./.github/actions/dependencies"
      - name: flake8
        run: make flake8
      - name: pycodestyle
        run: make pycodestyle
      - name: pylint
        run: make pylint
      - name: mypy
        run: make mypy